-- To create the entities

CREATE TABLE BRANCH (
    BRANCH_ID VARCHAR(10),
    BANK_NAME VARCHAR(15),
    BRANCH_NAME VARCHAR(20),
    ASSETS INT NOT NULL,
    PRIMARY KEY (BRANCH_ID)
);

CREATE TABLE CUSTOMER (
    CUSTOMER_ID VARCHAR(10),
    CUSTOMER_NAME VARCHAR(20),
    CUSTOMER_AGE INT,
    CUSTOMER_ADDRESS VARCHAR(20),
    CUSTOMER_PHONE INT,
    PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE ACCOUNT (
    ACCOUNT_NO INT,
    BRANCH_ID VARCHAR(10),
    ACCOUNT_TYPE VARCHAR(10),
    ACCOUNT_BALANCE INT,
    CUSTOMER_ID VARCHAR(10),
    PRIMARY KEY (ACCOUNT_NO),
    FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH (BRANCH_ID) ON DELETE CASCADE,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID) ON DELETE CASCADE
);

CREATE TABLE LOAN (
    LOAN_NUMBER INT,
    BRANCH_ID VARCHAR(10),
    AMOUNT INT,
    CUSTOMER_ID VARCHAR(10),
    PRIMARY KEY (LOAN_NUMBER),
    FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH (BRANCH_ID) ON DELETE CASCADE,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID) ON DELETE CASCADE
);

-- To solve the sub questions

-- a) Find all the customers who have atleast one account at the "Mangaluru" branch
SELECT CUSTOMER_ID, CUSTOMER_NAME
FROM CUSTOMER C, ACCOUNT A, BRANCH B
WHERE B.BRANCH_ID = A.BRANCH_ID AND A.CUSTOMER_ID = C.CUSTOMER_ID AND B.BRANCH_NAME = 'Mangaluru';

-- b) Find names of the depositors who have deposited highest amount among all the customers
SELECT CUSTOMER_ID, CUSTOMER_NAME, ACCOUNT_BALANCE
FROM CUSTOMER C, ACCOUNT A
WHERE C.CUSTOMER_ID = A.CUSTOMER_ID AND ACCOUNT_BALANCE = (
    SELECT MAX(ACCOUNT_BALANCE)
    FROM ACCOUNT
);

-- c) Retrieve the customer name and loan amount of a customer who borrowed a loan of more than 5,00,000
SELECT CUSTOMER_NAME, AMOUNT
FROM CUSTOMER C, LOAN L
WHERE C.CUSTOMER_ID = L.CUSTOMER_ID AND L.AMOUNT > 500000;

-- d) Retrieve the bank details of bank branch with maximum assets and minimum assets
(SELECT BANK_NAME, BRANCH_NAME, ASSETS
FROM BRANCH
WHERE ASSETS = (SELECT MAX(ASSETS) FROM BRANCH))
UNION
(SELECT BANK_NAME, BRANCH_NAME, ASSETS
FROM BRANCH
WHERE ASSETS = (SELECT MIN(ASSETS) FROM BRANCH));

-- e) Demonstrate how you delete all account tuples at every branch located in a specific city
DELETE FROM BRANCH WHERE BRANCH_NAME = 'Delhi';

-- ! NOTE: Before deleting, display the contents to be deleted for confirmation

