CREATE TABLE BRANCH (
    BRANCH_ID VARCHAR(10),
    BANK_NAME VARCHAR(15),
    BRANCH_NAME VARCHAR(20),
    ASSETS INT NOT NULL,
    PRIMARY KEY (BRANCH_ID)
);

CREATE TABLE LOAN (
    LOAN_NUMBER INT,
    BRANCH_ID VARCHAR(10),
    AMOUNT INT,
    CUSTOMER_ID VARCHAR(10),
    PRIMARY KEY (LOAN_NUMBER),
    FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH (BRANCH_ID) ON DELETE CASCADE,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID) ON DELETE CASCADE
);

CREATE TABLE CUSTOMER (
    CUSTOMER_ID VARCHAR(10),
    CUSTOMER_NAME VARCHAR(20),
    CUSTOMER_AGE INT,
    CUSTOMER_ADDRESS VARCHAR(20),
    CUSTOMER_PHONE INT,
    PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE ACCOUNT (
    ACCOUNT_NO INT,
    BRANCH_ID VARCHAR(10),
    ACCOUNT_TYPE VARCHAR(10),
    ACCOUNT_BALANCE INT,
    CUSTOMER_ID VARCHAR(10),
    PRIMARY KEY (ACCOUNT_NO),
    FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH (BRANCH_ID) ON DELETE CASCADE,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID) ON DELETE CASCADE
);
