-- TABLE CREATION & INSERTION

CREATE TABLE BRANCH (
    BRANCH_ID VARCHAR(10),
    BANK_NAME VARCHAR(15),
    BRANCH_NAME VARCHAR(20),
    ASSETS INT NOT NULL,
    PRIMARY KEY (BRANCH_ID)
);

INSERT INTO BRANCH VALUES ('&BRANCH_ID', '&BANK_NAME', '&BRANCH_NAME', '&ASSETS');
cnr01
Canara
Mangaluru
10000000
INSERT INTO BRANCH VALUES ('&BRANCH_ID', '&BANK_NAME', '&BRANCH_NAME', '&ASSETS');
cnr02
Canara
Mysore
140000000
INSERT INTO BRANCH VALUES ('&BRANCH_ID', '&BANK_NAME', '&BRANCH_NAME', '&ASSETS');
cnr03
Canara
Udupi
467000000
INSERT INTO BRANCH VALUES ('&BRANCH_ID', '&BANK_NAME', '&BRANCH_NAME', '&ASSETS');
sbi01
SBI
Hampankatta
156080000
INSERT INTO BRANCH VALUES ('&BRANCH_ID', '&BANK_NAME', '&BRANCH_NAME', '&ASSETS');
sbi02
SBI
Statebank
57000000
INSERT INTO BRANCH VALUES ('&BRANCH_ID', '&BANK_NAME', '&BRANCH_NAME', '&ASSETS');
sbi03
SBI
Mulki
75600000
INSERT INTO BRANCH VALUES ('&BRANCH_ID', '&BANK_NAME', '&BRANCH_NAME', '&ASSETS');
hdf01
HDFC
Delhi
753290000
INSERT INTO BRANCH VALUES ('&BRANCH_ID', '&BANK_NAME', '&BRANCH_NAME', '&ASSETS');
hdf02
HDFC
Kochi
743309000
INSERT INTO BRANCH VALUES ('&BRANCH_ID', '&BANK_NAME', '&BRANCH_NAME', '&ASSETS');
hdf03
HDFC
Munnar
52309000

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

CREATE TABLE CUSTOMER (
    CUSTOMER_ID VARCHAR(10),
    CUSTOMER_NAME VARCHAR(20),
    CUSTOMER_AGE INT,
    CUSTOMER_ADDRESS VARCHAR(20),
    CUSTOMER_PHONE INT,
    PRIMARY KEY (CUSTOMER_ID)
);

INSERT INTO CUSTOMER VALUES ('&CUSTOMER_ID', '&CUSTOMER_NAME', '&CUSTOMER_AGE', '&CUSTOMER_ADDRESS', '&CUSTOMER_PHONE');
4sf21bnk01
Achal Kumar
34
Malaysia
892713
INSERT INTO CUSTOMER VALUES ('&CUSTOMER_ID', '&CUSTOMER_NAME', '&CUSTOMER_AGE', '&CUSTOMER_ADDRESS', '&CUSTOMER_PHONE');
4sf21bnk02
Rishabh Singh
44
Iceland
447378
INSERT INTO CUSTOMER VALUES ('&CUSTOMER_ID', '&CUSTOMER_NAME', '&CUSTOMER_AGE', '&CUSTOMER_ADDRESS', '&CUSTOMER_PHONE');
4sf21bnk03
Aditya Pal
35
Goa
328947
INSERT INTO CUSTOMER VALUES ('&CUSTOMER_ID', '&CUSTOMER_NAME', '&CUSTOMER_AGE', '&CUSTOMER_ADDRESS', '&CUSTOMER_PHONE');
4sf21bnk04
Manjunath Rai
28
Gokarna
432783
INSERT INTO CUSTOMER VALUES ('&CUSTOMER_ID', '&CUSTOMER_NAME', '&CUSTOMER_AGE', '&CUSTOMER_ADDRESS', '&CUSTOMER_PHONE');
4sf21bnk05
Rishab Nayak
30
Bengaluru
989328
INSERT INTO CUSTOMER VALUES ('&CUSTOMER_ID', '&CUSTOMER_NAME', '&CUSTOMER_AGE', '&CUSTOMER_ADDRESS', '&CUSTOMER_PHONE');
4sf21bnk06
Michael Swamy
31
Kharagpur
323737
INSERT INTO CUSTOMER VALUES ('&CUSTOMER_ID', '&CUSTOMER_NAME', '&CUSTOMER_AGE', '&CUSTOMER_ADDRESS', '&CUSTOMER_PHONE');
4sf21bnk07
Sachin Padukone
40
Chennai
312739
INSERT INTO CUSTOMER VALUES ('&CUSTOMER_ID', '&CUSTOMER_NAME', '&CUSTOMER_AGE', '&CUSTOMER_ADDRESS', '&CUSTOMER_PHONE');
4sf21bnk08
Allison Burgers
25
Wadiya
137982

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

CREATE TABLE ACCOUNT (
    ACCOUNT_NO INT,
    BRANCH_ID VARCHAR(10),
    ACCOUNT_TYPE VARCHAR(10),
    ACCOUNT_BALANCE INT,
    CUSTOMER_ID VARCHAR(10),
    PRIMARY KEY (ACCOUNT_NO),
    FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH (BRANCH_ID) ON DELETE CASCADE,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID) ON DELETE CASCADE
);

INSERT INTO ACCOUNT VALUES ('&ACCOUNT_NO', '&BRANCH_ID', '&ACCOUNT_TYPE', '&ACCOUNT_BALANCE', '&CUSTOMER_ID');
123456
cnr01
Savings
509000
4sf21bnk01
INSERT INTO ACCOUNT VALUES ('&ACCOUNT_NO', '&BRANCH_ID', '&ACCOUNT_TYPE', '&ACCOUNT_BALANCE', '&CUSTOMER_ID');
116522
cnr03
Joint
14554000
4sf21bnk05
INSERT INTO ACCOUNT VALUES ('&ACCOUNT_NO', '&BRANCH_ID', '&ACCOUNT_TYPE', '&ACCOUNT_BALANCE', '&CUSTOMER_ID');
143265
sbi01
Joint
150000
4sf21bnk02
INSERT INTO ACCOUNT VALUES ('&ACCOUNT_NO', '&BRANCH_ID', '&ACCOUNT_TYPE', '&ACCOUNT_BALANCE', '&CUSTOMER_ID');
531245
sbi02
Savings
50000
4sf21bnk04
INSERT INTO ACCOUNT VALUES ('&ACCOUNT_NO', '&BRANCH_ID', '&ACCOUNT_TYPE', '&ACCOUNT_BALANCE', '&CUSTOMER_ID');
651341
hdf01
FD
509000
4sf21bnk03
INSERT INTO ACCOUNT VALUES ('&ACCOUNT_NO', '&BRANCH_ID', '&ACCOUNT_TYPE', '&ACCOUNT_BALANCE', '&CUSTOMER_ID');
312312
hdf03
FD
705000
4sf21bnk06

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

CREATE TABLE LOAN (
    LOAN_NUMBER INT,
    BRANCH_ID VARCHAR(10),
    AMOUNT INT,
    CUSTOMER_ID VARCHAR(10),
    PRIMARY KEY (LOAN_NUMBER),
    FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH (BRANCH_ID) ON DELETE CASCADE,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID) ON DELETE CASCADE
);

INSERT INTO LOAN VALUES ('&LOAN_NUMBER', '&BRANCH_ID', '&AMOUNT', '&CUSTOMER_ID');
123
cnr01
120000
4sf21bnk02
INSERT INTO LOAN VALUES ('&LOAN_NUMBER', '&BRANCH_ID', '&AMOUNT', '&CUSTOMER_ID');
124
sbi01
450000
4sf21bnk05
INSERT INTO LOAN VALUES ('&LOAN_NUMBER', '&BRANCH_ID', '&AMOUNT', '&CUSTOMER_ID');
456
cnr03
1120000
4sf21bnk01
INSERT INTO LOAN VALUES ('&LOAN_NUMBER', '&BRANCH_ID', '&AMOUNT', '&CUSTOMER_ID');
876
cnr02
1270000
4sf21bnk03
INSERT INTO LOAN VALUES ('&LOAN_NUMBER', '&BRANCH_ID', '&AMOUNT', '&CUSTOMER_ID');
435
hdf01
1920000
4sf21bnk06

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

-- To solve the sub questions

-- a) Find all the customers who have atleast one account at the "Mangaluru" branch
SELECT C.CUSTOMER_ID, C.CUSTOMER_NAME
FROM CUSTOMER C, ACCOUNT A, BRANCH B
WHERE B.BRANCH_ID = A.BRANCH_ID AND A.CUSTOMER_ID = C.CUSTOMER_ID AND B.BRANCH_NAME = 'Mangaluru';

-- b) Find names of the depositors who have deposited highest amount among all the customers
SELECT C.CUSTOMER_ID, C.CUSTOMER_NAME, ACCOUNT_BALANCE
FROM CUSTOMER C, ACCOUNT A
WHERE C.CUSTOMER_ID = A.CUSTOMER_ID AND ACCOUNT_BALANCE = (SELECT MAX(ACCOUNT_BALANCE) FROM ACCOUNT);

-- c) Retrieve the customer name and loan amount of a customer who borrowed a loan of more than 5,00,000
SELECT CUSTOMER_NAME, AMOUNT
FROM CUSTOMER C, LOAN L
WHERE C.CUSTOMER_ID = L.CUSTOMER_ID AND L.AMOUNT > 500000;

-- d) Retrieve the bank details of bank branch with maximum assets and minimum assets
(SELECT BANK_NAME, BRANCH_NAME, ASSETS
FROM BRANCH
WHERE ASSETS = (SELECT MAX(ASSETS) FROM BRANCH))
UNION
(SELECT BANK_NAME, BRANCH_NAME, ASSETS
FROM BRANCH
WHERE ASSETS = (SELECT MIN(ASSETS) FROM BRANCH));

-- e) Demonstrate how you delete all account tuples at every branch located in a specific city
DELETE FROM BRANCH WHERE BRANCH_NAME = 'Delhi';

-- ! NOTE: Before deleting, display the contents to be deleted for confirmation

