-- TABLE CREATION & INSERTION

CREATE TABLE STUDENT (
	USN VARCHAR(20),
	SNAME CHAR(15),
	ADDRESS VARCHAR(20),
	PHONE INTEGER,
	GENDER CHAR(6),
	PRIMARY KEY (USN)
);

INSERT INTO STUDENT VALUES ('&USN', '&SNAME', '&ADDRESS', '&PHONE', '&GENDER');
SF001
RAHUL
MANJESHWARA
12345
MALE
INSERT INTO STUDENT VALUES ('&USN', '&SNAME', '&ADDRESS', '&PHONE', '&GENDER');
SF002
GANESH
MANGALORE
54345
MALE
INSERT INTO STUDENT VALUES ('&USN', '&SNAME', '&ADDRESS', '&PHONE', '&GENDER');
SF003
KEERTHI
ATTAVAR
75676
MALE
INSERT INTO STUDENT VALUES ('&USN', '&SNAME', '&ADDRESS', '&PHONE', '&GENDER');
SF004
CHELSEA
KANKANADY
35434
FEMALE
INSERT INTO STUDENT VALUES ('&USN', '&SNAME', '&ADDRESS', '&PHONE', '&GENDER');
SF005
RADHIKA
BENDORWELL
54879
FEMALE
INSERT INTO STUDENT VALUES ('&USN', '&SNAME', '&ADDRESS', '&PHONE', '&GENDER');
SF006
ACHAL
KONAJE
87565
MALE

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

CREATE TABLE SEMSEC (
	SSID VARCHAR(20),
	SEM INTEGER,
	SEC CHAR(5),
	PRIMARY KEY (SSID)
);

INSERT INTO SEMSEC VALUES ('&SSID', '&SEM', '&SEC');
SS01
3
AIML
INSERT INTO SEMSEC VALUES ('&SSID', '&SEM', '&SEC');
SS02
3
AIDS
INSERT INTO SEMSEC VALUES ('&SSID', '&SEM', '&SEC');
SS03
5
AIML
INSERT INTO SEMSEC VALUES ('&SSID', '&SEM', '&SEC');
SS04
5
AIDS
INSERT INTO SEMSEC VALUES ('&SSID', '&SEM', '&SEC');
SS05
7
AIML
INSERT INTO SEMSEC VALUES ('&SSID', '&SEM', '&SEC');
SS06
3
CSA
INSERT INTO SEMSEC VALUES ('&SSID', '&SEM', '&SEC');
SS07
3
CSB
INSERT INTO SEMSEC VALUES ('&SSID', '&SEM', '&SEC');
SS08
5
CSA
INSERT INTO SEMSEC VALUES ('&SSID', '&SEM', '&SEC');
SS09
5
CSB
INSERT INTO SEMSEC VALUES ('&SSID', '&SEM', '&SEC');
SS10
5
CSC

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

CREATE TABLE CLASS (
	USN VARCHAR(20),
	SSID VARCHAR(20),
	PRIMARY KEY (USN, SSID),
	FOREIGN KEY (USN) REFERENCES STUDENT (USN) ON DELETE CASCADE,
	FOREIGN KEY (SSID) REFERENCES SEMSEC (SSID) ON DELETE CASCADE
);

INSERT INTO CLASS VALUES ('&USN', '&SSID');
SF001
SS01
INSERT INTO CLASS VALUES ('&USN', '&SSID');
SF002
SS01
INSERT INTO CLASS VALUES ('&USN', '&SSID');
SF003
SS02
INSERT INTO CLASS VALUES ('&USN', '&SSID');
SF004
SS03
INSERT INTO CLASS VALUES ('&USN', '&SSID');
SF005
SS03
INSERT INTO CLASS VALUES ('&USN', '&SSID');
SF006
SS08

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

CREATE TABLE COURSE (
	SUBCODE VARCHAR(15),
	TITLE VARCHAR(20),
	SEM CHAR(5),
	CREDITS INTEGER,
	PRIMARY KEY (SUBCODE)
);

INSERT INTO COURSE VALUES ('&SUBCODE', '&TITLE', '&SEM', '&CREDITS');
21CS31
C PROGRAMMING
3
3
INSERT INTO COURSE VALUES ('&SUBCODE', '&TITLE', '&SEM', '&CREDITS');
21CS32
JAVA
3
2
INSERT INTO COURSE VALUES ('&SUBCODE', '&TITLE', '&SEM', '&CREDITS');
21CS33
SYSTEM DESIGN
3
2
INSERT INTO COURSE VALUES ('&SUBCODE', '&TITLE', '&SEM', '&CREDITS');
21CS34
DATA STRUCTURES
3
3
INSERT INTO COURSE VALUES ('&SUBCODE', '&TITLE', '&SEM', '&CREDITS');
21CS51
ARTIFICIAL INTELLIGENCE
5
2
INSERT INTO COURSE VALUES ('&SUBCODE', '&TITLE', '&SEM', '&CREDITS');
21CS52
MATHS FOR ML
5
3
INSERT INTO COURSE VALUES ('&SUBCODE', '&TITLE', '&SEM', '&CREDITS');
21CS54
ALGORITHMS
5
2
INSERT INTO COURSE VALUES ('&SUBCODE', '&TITLE', '&SEM', '&CREDITS');
21CS71
DEEP LEARNING
7
2
INSERT INTO COURSE VALUES ('&SUBCODE', '&TITLE', '&SEM', '&CREDITS');
21CS75
NETWORKING
7
3

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

CREATE TABLE IAMARKS (
	USN VARCHAR(20),
	SUBCODE VARCHAR(15),
	SSID VARCHAR(20),
	TEST1 INTEGER,
	TEST2 INTEGER,
	TEST3 INTEGER,
	FINALIA INTEGER,
	PRIMARY KEY (USN, SUBCODE, SSID),
	FOREIGN KEY (USN) REFERENCES STUDENT (USN) ON DELETE CASCADE,
	FOREIGN KEY (SUBCODE) REFERENCES COURSE (SUBCODE) ON DELETE CASCADE,
	FOREIGN KEY (SSID) REFERENCES SEMSEC (SSID) ON DELETE CASCADE
);

INSERT INTO IAMARKS VALUES ('&USN', '&SUBCODE', '&SSID', '&TEST1', '&TEST2', '&TEST3', '&FINALIA');
SF001
21CS31
SS01
25
20
26
90
INSERT INTO IAMARKS VALUES ('&USN', '&SUBCODE', '&SSID', '&TEST1', '&TEST2', '&TEST3', '&FINALIA');
SF002
21CS34
SS01
24
21
25
94
INSERT INTO IAMARKS VALUES ('&USN', '&SUBCODE', '&SSID', '&TEST1', '&TEST2', '&TEST3', '&FINALIA');
SF001
21CS33
SS01
21
27
26
80
INSERT INTO IAMARKS VALUES ('&USN', '&SUBCODE', '&SSID', '&TEST1', '&TEST2', '&TEST3', '&FINALIA');
SF006
21CS52
SS08
18
25
30
99
INSERT INTO IAMARKS VALUES ('&USN', '&SUBCODE', '&SSID', '&TEST1', '&TEST2', '&TEST3', '&FINALIA');
SF004
21CS54
SS03
21
21
26
88

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
